### ISSUE TITLE
Add Typewriter Animation Support for Marked HTML Content in React

### ISSUE THREAD

**Issue by Swasti008** [kalviumcommunity/S59_Swasti_Capstone_OrbitIQ#39]
I am working on an individual project where I plan to use the marked library to convert markdown responses from an AI into HTML. To improve user experience, I want to display this HTML content with a typewriter animation effect. Currently, I have a Typewriter component that handles plain text animation, but I need it to support HTML content generated by marked.

**Desired Functionality:**
1. HTML Support: Extend the Typewriter component to handle HTML content by maintaining the HTML structure while animating the text.
2. Seamless Integration: Ensure the solution integrates smoothly with the marked library and existing React components.
3. Add css to markdown-response elements like h1,ul,li tags.

**Comment by ananyatewari** [comment]
Hey

Can I work on this ?

**Comment by Swasti008** [comment]
Yes ,Sure.

**Comment by Swasti008** [comment]
Thanks for contribution 
merged into main branch #40
