### ISSUE TITLE
Add CSS for Chatbot UI

### ISSUE THREAD

**Issue by Swasti008** [kalviumcommunity/S59_Swasti_Capstone_OrbitIQ#41]
I am working on my capstone project, OrbitIQ, and I have implemented a chatbot component that provides AI responses. However, I need help with styling the chatbot UI to enhance its visual appearance and user experience. Here are the specific requirements and improvements I am looking for:

**Current Implementation**:-
1. GenAI Component: This component displays AI responses and handles the logic to send the question as request to server.
2. Typewriter Component: This component animates the AI response text.
3. ChatBotUI: main component which renders all the related components.

**Desired Improvements**:-
1. Welcome Message:
Display a default welcome message, "Welcome to OrbitIQ, I am your assistant. How can I assist you?" when the component mounts.
Style the welcome message to be visually appealing.

2. Chatbot Icon:
Display a small icon (robot) on the left side of the message bubble, similar to popular chat UIs like ChatGPT.

3. Message Bubbles:
Style the AI response message bubble to be visually distinct, with appropriate padding, background color, and border radius.

Example of Desired Style
Here is an example of the desired styling for the chatbot UI:
![image](https://github.com/kalviumcommunity/S59_Swasti_Capstone_OrbitIQ/assets/144793835/8c1d459e-a55a-4289-9628-c4282ccf3452)

Chatbot Icon image is provided already in asserts :- chatbot.png and chat.png (small left icon).

**Comment by Merlinkk** [comment]
Hey @Swasti008 , I would like to work on this issue.

**Comment by Swasti008** [comment]
Sure and just want to inform you that I have made a file under css folder for LunaAI component css ,so just add the css there.

**Comment by Merlinkk** [comment]
Hey, @Swasti008 just finished. #43 Please Review

**Comment by Swasti008** [comment]
#43 Merged into main branch.
Thanks for contribution @Merlinkk.

**Comment by Swasti008** [comment]
https://github.com/kalviumcommunity/S59_Swasti_Capstone_OrbitIQ/pull/43 Merged into main branch.
Thanks for contribution @Merlinkk.
