### ISSUE TITLE
Implement Rate Limiter for /google-genai Endpoint and Display Popup on Client Side for 429 Errors

### ISSUE THREAD

**Issue by Swasti008** [kalviumcommunity/S59_Swasti_Capstone_OrbitIQ#44]
Currently,I have the logic to get responses from AI in place. This issue aims to enhance the functionality by implementing a rate limiter on the /google-genai endpoint and displaying a popup on the client side when a 429 error (Too Many Requests) occurs.

**Tasks:**
 **Server-Side**: 

      -  Implement Rate Limiter for /google-genai Endpoint
      -  Install express-rate-limit if not already installed.
      -  Set up a rate limiter for the /google-genai endpoint, limiting to 10 requests per 10 minutes.
      -  Add custom error handling for the rate limiter to provide meaningful error messages.

**Client-Side:** 

      - Handle 429 Error
      - Modify the client-side logic to handle 429 errors.
      - Display a popup or alert when a 429 error is received from the server, informing the user that they have exceeded the number of 
        allowed requests and should try again later.

**Comment by Abhinandan-4321** [comment]
Hi, Can i work on this issue??
I have already implemented this in past.

**Comment by Swasti008** [comment]
Sure,  Can I get your email to send the required .env details?

**Comment by Abhinandan-4321** [comment]
abhinandan.gupta@kalvium.community
you can send the enviornment variables on this mail ID.

**Comment by Swasti008** [comment]
Thanks for contribution @Abhinandan-4321 .
Merged PR:- #45 and closing this issue.
